puzzles = [
    {"kysymys": "Mikä eläin sanoo 'hau hau'?", "vastaus": "koira"},
    {"kysymys": "Paljonko on 5 + 5?", "vastaus": "10"},
    {"kysymys": "Minkä värinen banaani yleensä on?", "vastaus": "keltainen"},
    {"kysymys": "Mikä eläin tunnetaan siitä, että se sanoo 'ammuu'?", "vastaus": "lehmä"},
    {"kysymys": "Kuinka monta silmää ihmisellä yleensä on?", "vastaus": "2"},
    {"kysymys": "Mikä hedelmä on yleensä punainen ja siinä on siemeniä pinnalla?", "vastaus": "mansikka"},
    {"kysymys": "Paljonko on 10 - 3?", "vastaus": "7"},
    {"kysymys": "Mikä eläin tunnetaan pitkästä kärsästään?", "vastaus": "norsu"},
    {"kysymys": "Mitä eläintä kutsutaan usein ihmisen parhaaksi ystäväksi?", "vastaus": "koira"},
    {"kysymys": "Mikä päivä tulee perjantain jälkeen?", "vastaus": "lauantai"},

    {"kysymys": "Paljonko on 2 * 6?", "vastaus": "12"},
    {"kysymys": "Mikä juoma valmistetaan yleensä kaakaosta ja maidosta?", "vastaus": "kaakao"},
    {"kysymys": "Mikä eläin sanoo 'miau'?", "vastaus": "kissa"},
    {"kysymys": "Mikä on vastakohta sanalle 'iso'?", "vastaus": "pieni"},
    {"kysymys": "Kuinka monta jalkaa koiralla on?", "vastaus": "4"},
    {"kysymys": "Mikä hedelmä on tunnettu keltaisesta väristään ja kuorestaan?", "vastaus": "banaani"},
    {"kysymys": "Paljonko on 20 / 2?", "vastaus": "10"},
    {"kysymys": "Mikä eläin on tunnettu siitä, että se kantaa poikastaan pussissa?", "vastaus": "kenguru"},
    {"kysymys": "Mikä vuodenaika tulee kesän jälkeen?", "vastaus": "syksy"},
    {"kysymys": "Mikä on Suomen pääkaupunki?", "vastaus": "helsinki"},

    {"kysymys": "Mikä supersankari käyttää lepakkoa symbolinaan?", "vastaus": "batman"},
    {"kysymys": "Paljonko on 7 + 8?", "vastaus": "15"},
    {"kysymys": "Mikä eläin on tunnettu mustavalkoisista raidoistaan?", "vastaus": "seepra"},
    {"kysymys": "Mitä eläintä voisi löytää maatilalta ja se munii munia?", "vastaus": "kana"},
    {"kysymys": "Mikä väri syntyy, kun punainen ja keltainen sekoitetaan?", "vastaus": "oranssi"},
    {"kysymys": "Kuinka monta sormea on yhdessä kädessä?", "vastaus": "5"},
    {"kysymys": "Paljonko on 3 * 3?", "vastaus": "9"},
    {"kysymys": "Mikä eläin tunnetaan siitä, että se rakastaa hunajaa?", "vastaus": "karhu"},
    {"kysymys": "Mikä on viikon ensimmäinen päivä?", "vastaus": "maanantai"},
    {"kysymys": "Mikä planeetta tunnetaan punaisena planeettana?", "vastaus": "mars"},

    {"kysymys": "Mikä hedelmä voi olla vihreä tai punainen ja kasvaa puussa?", "vastaus": "omena"},
    {"kysymys": "Paljonko on 100 - 50?", "vastaus": "50"},
    {"kysymys": "Mikä eläin tunnetaan pitkästä kaulastaan?", "vastaus": "kirahvi"},
    {"kysymys": "Mikä on Suomen kansalliseläin?", "vastaus": "karhu"},
    {"kysymys": "Kuinka monta päivää viikonloppuun yleensä kuuluu?", "vastaus": "2"},
    {"kysymys": "Mikä supersankari heiluu verkkojen avulla?", "vastaus": "spiderman"},
    {"kysymys": "Paljonko on 4 + 6?", "vastaus": "10"},
    {"kysymys": "Mikä eläin osaa lentää ja sanoo usein 'tsirp'?", "vastaus": "lintu"},
    {"kysymys": "Mikä väri syntyy, kun sininen ja keltainen sekoitetaan?", "vastaus": "vihreä"},
    {"kysymys": "Mikä on vuoden viimeinen kuukausi?", "vastaus": "joulukuu"},

    {"kysymys": "Mikä eläin näyttää hevoselta ja sillä on raidat?", "vastaus": "seepra"},
    {"kysymys": "Paljonko on 8 + 2?", "vastaus": "10"},
    {"kysymys": "Mikä ruoka valmistetaan usein jauhelihasta ja sämpylästä?", "vastaus": "hampurilainen"},
    {"kysymys": "Kuinka monta pyörää tavallisessa polkupyörässä on?", "vastaus": "2"},
    {"kysymys": "Mikä eläin tunnetaan hitaasta liikkumisestaan?", "vastaus": "laiskiainen"},
    {"kysymys": "Mikä on vastakohta sanalle 'kuuma'?", "vastaus": "kylmä"},
    {"kysymys": "Paljonko on 6 * 5?", "vastaus": "30"},
    {"kysymys": "Mikä herkku valmistetaan usein suklaasta?", "vastaus": "suklaa"},
    {"kysymys": "Mikä eläin sanoo 'muu'?", "vastaus": "lehmä"},
    {"kysymys": "Kuinka monta kuukautta vuodessa on?", "vastaus": "12"},

    {"kysymys": "Mikä on Suomen kansalliskukka?", "vastaus": "kielo"},
    {"kysymys": "Paljonko on 15 + 5?", "vastaus": "20"},
    {"kysymys": "Mikä eläin tunnetaan siitä, että se rakentaa patoja?", "vastaus": "majava"},
    {"kysymys": "Mikä on joulupukin tärkein kulkuväline tarinoissa?", "vastaus": "reki"},
    {"kysymys": "Kuinka monta jalkaa hämähäkillä on?", "vastaus": "8"},
    {"kysymys": "Mikä hedelmä tunnetaan oranssista väristään?", "vastaus": "appelsiini"},
    {"kysymys": "Paljonko on 30 / 3?", "vastaus": "10"},
    {"kysymys": "Mikä eläin tunnetaan mustavalkoisena ja syö bambua?", "vastaus": "panda"},
    {"kysymys": "Mikä kuukausi tulee joulukuun jälkeen?", "vastaus": "tammikuu"},
    {"kysymys": "Mikä on veden kemiallinen kaava?", "vastaus": "h2o"},

    {"kysymys": "Mikä eläin tunnetaan siitä, että se antaa maitoa?", "vastaus": "lehmä"},
    {"kysymys": "Paljonko on 9 + 1?", "vastaus": "10"},
    {"kysymys": "Mikä on vastakohta sanalle 'ylös'?", "vastaus": "alas"},
    {"kysymys": "Mikä eläin on tunnettu hunajasta ja mehiläisistä?", "vastaus": "mehiläinen"},
    {"kysymys": "Kuinka monta korvaa ihmisellä yleensä on?", "vastaus": "2"},
    {"kysymys": "Mikä on Suomen naapurimaa lännessä?", "vastaus": "ruotsi"},
    {"kysymys": "Paljonko on 12 - 2?", "vastaus": "10"},
    {"kysymys": "Mikä eläin tunnetaan siitä, että se vaihtaa väriä?", "vastaus": "kameleontti"},
    {"kysymys": "Mikä väri saadaan sekoittamalla mustaa ja valkoista?", "vastaus": "harmaa"},
    {"kysymys": "Mikä on vuoden ensimmäinen kuukausi?", "vastaus": "tammikuu"},

    {"kysymys": "Mikä eläin sanoo 'röh röh'?", "vastaus": "sika"},
    {"kysymys": "Paljonko on 11 + 4?", "vastaus": "15"},
    {"kysymys": "Mikä on Suomen suurin järvi?", "vastaus": "saimaa"},
    {"kysymys": "Mikä eläin tunnetaan erittäin nopeana juoksijana?", "vastaus": "gepardi"},
    {"kysymys": "Kuinka monta vuodenaikaa Suomessa on?", "vastaus": "4"},
    {"kysymys": "Mikä ruoka on pyöreä, siinä on usein tomaattikastiketta ja juustoa?", "vastaus": "pizza"},
    {"kysymys": "Paljonko on 7 * 2?", "vastaus": "14"},
    {"kysymys": "Mikä eläin kantaa kotiaan selässään?", "vastaus": "etana"},
    {"kysymys": "Mikä on joulun suosittu punainen marja?", "vastaus": "puolukka"},
    {"kysymys": "Mikä taivaalla näkyvä kappale valaisee yöllä?", "vastaus": "kuu"},
]

