puzzles = [
    {"kysymys": "Mikä on Australian pääkaupunki?", "vastaus": "canberra"},
    {"kysymys": "Missä maassa Eiffel-torni sijaitsee?", "vastaus": "ranska"},
    {"kysymys": "Mikä on Japanin pääkaupunki?", "vastaus": "tokio"},
    {"kysymys": "Missä kaupungissa Colosseum sijaitsee?", "vastaus": "rooma"},
    {"kysymys": "Mikä maa tunnetaan tulppaaneista ja tuulimyllyistä?", "vastaus": "alankomaat"},
    {"kysymys": "Mikä on Kanadan pääkaupunki?", "vastaus": "ottawa"},
    {"kysymys": "Missä maassa Machu Picchu sijaitsee?", "vastaus": "peru"},
    {"kysymys": "Mikä on Espanjan pääkaupunki?", "vastaus": "madrid"},
    {"kysymys": "Mikä maa tunnetaan saunasta ja tuhansista järvistä?", "vastaus": "suomi"},
    {"kysymys": "Missä kaupungissa Vapaudenpatsas sijaitsee?", "vastaus": "new york"},

    {"kysymys": "Mikä on Italian pääkaupunki?", "vastaus": "rooma"},
    {"kysymys": "Missä maassa Taj Mahal sijaitsee?", "vastaus": "intia"},
    {"kysymys": "Mikä on Islannin pääkaupunki?", "vastaus": "reykjavik"},
    {"kysymys": "Mikä maa tunnetaan muinaisesta pyramidialueesta Gizassa?", "vastaus": "egypti"},
    {"kysymys": "Missä kaupungissa Big Ben sijaitsee?", "vastaus": "lontoo"},
    {"kysymys": "Mikä on Portugalin pääkaupunki?", "vastaus": "lissabon"},
    {"kysymys": "Missä maassa Santorinin saari sijaitsee?", "vastaus": "kreikka"},
    {"kysymys": "Mikä on Norjan pääkaupunki?", "vastaus": "oslo"},
    {"kysymys": "Mikä maa tunnetaan Alpeista ja suklaasta?", "vastaus": "sveitsi"},
    {"kysymys": "Missä kaupungissa Burj Khalifa sijaitsee?", "vastaus": "dubai"},

    {"kysymys": "Mikä on Thaimaan pääkaupunki?", "vastaus": "bangkok"},
    {"kysymys": "Missä maassa Niagaran putoukset sijaitsevat?", "vastaus": "kanada"},
    {"kysymys": "Mikä on Uuden-Seelannin pääkaupunki?", "vastaus": "wellington"},
    {"kysymys": "Missä maassa Angkor Wat sijaitsee?", "vastaus": "kambodza"},
    {"kysymys": "Mikä on Brasilian pääkaupunki?", "vastaus": "brasilia"},
    {"kysymys": "Missä kaupungissa Sagrada Família sijaitsee?", "vastaus": "barcelona"},
    {"kysymys": "Mikä on Etelä-Korean pääkaupunki?", "vastaus": "seoul"},
    {"kysymys": "Mikä maa tunnetaan nimellä 'Tuhansien järvien maa'?", "vastaus": "suomi"},
    {"kysymys": "Missä maassa Petra sijaitsee?", "vastaus": "jordania"},
    {"kysymys": "Mikä on Meksikon pääkaupunki?", "vastaus": "mexico city"},

    {"kysymys": "Mikä maa on pinta-alaltaan maailman suurin?", "vastaus": "venäjä"},
    {"kysymys": "Mikä on maailman pienin valtio?", "vastaus": "vatikaani"},
    {"kysymys": "Mikä maa sijaitsee sekä Euroopassa että Aasiassa?", "vastaus": "turkki"},
    {"kysymys": "Mikä on Kreikan pääkaupunki?", "vastaus": "ateena"},
    {"kysymys": "Mikä maa tunnetaan revontulista ja geotermisistä lähteistään?", "vastaus": "islanti"},
    {"kysymys": "Missä maassa Kilimanjaro sijaitsee?", "vastaus": "tansania"},
    {"kysymys": "Mikä on Argentiinan pääkaupunki?", "vastaus": "buenos aires"},
    {"kysymys": "Missä kaupungissa Christ the Redeemer -patsas sijaitsee?", "vastaus": "rio de janeiro"},
    {"kysymys": "Mikä on Irlannin pääkaupunki?", "vastaus": "dublin"},
    {"kysymys": "Missä maassa Galápagossaaret sijaitsevat?", "vastaus": "ecuador"},

    {"kysymys": "Mikä on Marokon pääkaupunki?", "vastaus": "rabat"},
    {"kysymys": "Missä maassa Sahara sijaitsee?", "vastaus": "egypti"},
    {"kysymys": "Mikä on Itävallan pääkaupunki?", "vastaus": "wien"},
    {"kysymys": "Missä kaupungissa Akropolis sijaitsee?", "vastaus": "ateena"},
    {"kysymys": "Mikä maa tunnetaan nimellä 'nousevan auringon maa'?", "vastaus": "japani"},
    {"kysymys": "Mikä on Vietnamin pääkaupunki?", "vastaus": "hanoi"},
    {"kysymys": "Missä maassa Dubrovnik sijaitsee?", "vastaus": "kroatia"},
    {"kysymys": "Mikä on Sveitsin pääkaupunki?", "vastaus": "bern"},
    {"kysymys": "Missä maassa Mount Everest sijaitsee?", "vastaus": "nepal"},
    {"kysymys": "Mikä on Yhdysvaltojen pääkaupunki?", "vastaus": "washington"},

    {"kysymys": "Mikä on Kenian pääkaupunki?", "vastaus": "nairobi"},
    {"kysymys": "Missä maassa Cinque Terre sijaitsee?", "vastaus": "italia"},
    {"kysymys": "Mikä on Saksan pääkaupunki?", "vastaus": "berliini"},
    {"kysymys": "Missä maassa Alhambra sijaitsee?", "vastaus": "espanja"},
    {"kysymys": "Mikä on Tanskan pääkaupunki?", "vastaus": "kööpenhamina"},
    {"kysymys": "Missä maassa Sininen moskeija sijaitsee Istanbulissa?", "vastaus": "turkki"},
    {"kysymys": "Mikä on Etelä-Afrikan tunnettu matkailukaupunki Kapkaupunki englanniksi?", "vastaus": "cape town"},
    {"kysymys": "Missä maassa Bali sijaitsee?", "vastaus": "indonesia"},
    {"kysymys": "Mikä on Filippiinien pääkaupunki?", "vastaus": "manila"},
    {"kysymys": "Missä maassa Amalfin rannikko sijaitsee?", "vastaus": "italia"},

    {"kysymys": "Mikä maa käyttää valuuttana jeniä?", "vastaus": "japani"},
    {"kysymys": "Mikä maa käyttää valuuttana kruunua ja jonka pääkaupunki on Tukholma?", "vastaus": "ruotsi"},
    {"kysymys": "Mikä on Egyptin pääkaupunki?", "vastaus": "kairo"},
    {"kysymys": "Missä maassa Serengetin kansallispuisto sijaitsee?", "vastaus": "tansania"},
    {"kysymys": "Mikä on Chilen pääkaupunki?", "vastaus": "santiago"},
    {"kysymys": "Missä maassa Atacaman autiomaa sijaitsee?", "vastaus": "chile"},
    {"kysymys": "Mikä on Indonesian pääkaupunki?", "vastaus": "jakarta"},
    {"kysymys": "Missä maassa Bora Bora sijaitsee?", "vastaus": "ranska"},
    {"kysymys": "Mikä on Belgian pääkaupunki?", "vastaus": "brussel"},
    {"kysymys": "Missä maassa Malediivit sijaitsevat?", "vastaus": "malediivit"},
]
